version: '3.8'
services:
  frontend_server:
    image: tbr06057/react_portfolio_app:0.0.1
    restart: 'on-failure'
    ports:
      - 80:80
    networks:
      - portfolio-service

  backend_server:
    image: tbr06057/node_portfolio_app:0.0.1
    restart: 'on-failure'
    ports:
      - 5001:5001
    networks:
      - portfolio-service

networks:
  portfolio-service:
